### PR TITLE
Use install_local from devtools instead from remotes to reduce transitive dependencies

### PR DESCRIPTION
**Pull request by dbast**
Also update travis.yml to current standards, see https://docs.travis-ci.com/user/languages/r

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! The travis changes are unrelated, so ideally they should not be in this PR.

Why is devtools a better option here?

**Comment by dbast** [comment]
Well the travis changes are maybe not that unrelated, as without travis seems not to build anymore, see https://travis-ci.org/dbast/cyclocomp/builds/402405698 

I can split it into two PRs if you like, but they then depend on each other.

Why devtools:
- Almost everybody seems to already have it installed, this just avoids a dependency and its transitive dependencies
- even the cyclocomb/README.md mentions devtools::install_github("MangoTheCat/cyclocomp") instead of remotes::install_github(...)
- I later would like to bring cyclocomp to https://anaconda.org/conda-forge / https://github.com/conda-forge, where r-devtools is available but not r-remotes and packaging r-remotes does not make so much sense the way conda works, where packages are installed via public / private conda channels.

**Comment by gaborcsardi** [comment]
> Almost everybody seems to already have it installed, this just avoids a dependency and its transitive dependencies

Compare  http://crandeps.r-pkg.org/deps/remotes and http://crandeps.r-pkg.org/deps/devtools

> even the cyclocomb/README.md mentions devtools::install_github("MangoTheCat/cyclocomp") instead of remotes::install_github(...)

That is for the development version, and irrelevant for most people. Now I think that it  should not  be in the README at all. People should install from CRAN.

> I later would like to bring cyclocomp to...

remotes has no hard dependencies and no compiled code, so it will be easy to package it, I think.

**Comment by dbast** [comment]
Ok, sounds reasonable. Will close the pull request. Thanks!

**Pull request closed without merging**
